### ISSUE TITLE
start-md-server.sh resets modified MapRotation

### ISSUE THREAD

**Issue by waldfee** [Tetricz/docker-mordhau-server#3]
Initial Situation:

- Gamemode is set to "DM"
- on first start, a Game1.ini is created with this MapRotation:
-- MapRotation=FFA_ThePit
-- MapRotation=FFA_Contraband
-- MapRotation=FFA_Taiga
-- MapRotation=FFA_Grad
-- MapRotation=FFA_MountainPeak
-- MapRotation=FFA_Camp
-- MapRotation=FFA_Tourney

What I do:

- edit Game1.ini so fewer maps are in the map rotation

What I expect:

- on restarting the docker container those maps are used

What happens:

- the map rotation list is overwritten with the default one

I could not find the reason why other things in the Game.ini are not overwritten (like server name). Which is strange because start-md-server.sh checks if the file already exists

**Comment by Tetricz** [comment]
That's odd. It literally is supposed to check to see if the Game.ini file for the server is there. If it is there then it does nothing and if it doesn't, it creates it with the Gamemode chosen.

I can't recreate this issue.
